# Generated by Django 5.2.8 on 2025-12-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fitnessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessprofile',
            name='goal',
            field=models.CharField(choices=[('cut', 'Fat Loss/ Cut'), ('maintain', 'Maintain'), ('lean_bulk', 'Lean Bulk'), ('bulk', 'Bulk/ Muscle Gain')], max_length=10),
        ),
    ]
